language: java
jdk: openjdk8

after_success:
   - mvn clean install jacoco:prepare-agent jacoco:report
   - mvn -DmemoryInMB=2000 -Dcores=2 evosuite:generate evosuite:export test
   - bash <(curl -s https://codecov.io/bash)
